### ISSUE TITLE
Not generating blocks.cfg when railcraft beta installed

### ISSUE THREAD

**Issue by kragnoth** [bonii-xx/HarvestTweaks#1]
After going through trying to figure out what was causing the blocks.cfg file to not generate, I have tracked it to railcraft beta.  Looking through latest client logs, all other mods seem to be generating errors and skipping blocks properly, but railcraft is never mentioned in the log.  

Reproducing this error only requires installing railcraft.  Error is resolved by removing railcraft.

**Comment by bonii-xx** [comment]
Fixed in 0.1.1, also made CJ aware that his quarried stone is missing a pickaxe as tool. Also I'm gonna close this repo, you know, because of the main one being in slimeknights. ;)
